apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: h0k9p9lr5-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: h0k9p9lr5-python 
  name: h0k9p9lr5-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: h0k9p9lr5-python 
